NAND-240 adding delete all resources script
lantanagroup/nandina pull request #48
Opened 2021-01-08 02:18 UTC by bnorris2

NAND-240 adding delete all resources script

2021-01-08 03:09 UTC, seanmcilvenna requested changes

2021-01-08 03:09 UTC, seanmcilvenna commented on query/src/test/java/ResourceLoader.java
> +        deleteResource("Condition", conditionIds);
Add `Encounter`, `Coverage`, `MedicationRequest`, `Observation`, `Procedure`, `Location`

2021-01-08 03:09 UTC, seanmcilvenna commented on query/src/test/java/ResourceLoader.java
> +        deleteResource("Condition", conditionIds);
and `AllergyIntolerance`

2021-01-08 03:09 UTC, seanmcilvenna commented on query/src/test/java/ResourceLoader.java
> +        HttpClient client = HttpClient.newBuilder().build();
Can we (reasonably) move this to the CLI as a separate main() method that accepts the "fhirServerBase" as a parameter? Would like to be able to run this without IntelliJ, and run it against various servers without changing code...

2021-01-09 14:47 UTC, bnorris2 commented on query/src/test/java/ResourceLoader.java
> +        deleteResource("Condition", conditionIds);
i've added these...and the expunge

2021-01-09 19:33 UTC, seanmcilvenna approved these changes

2021-01-09 19:34 UTC, merged